#!/usr/bin/env bash
#process and pid file

echo $$ > /var/run/myscript.pid
trap 'echo "I havte the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
