#!/usr/bin/env bash
#managing my process

pid="/var/run/my_process.pid"

if [ "$1" = "start" ]; then
	./manage_my_process &
	echo $! > $pid
	echo "manage_my_process started"

elif [ "$2" = "stop" ]; then
	kill "$(cat $pid)"
	rm "$pid"
	echo "manage_my_process stopped"

elif [ "$3" = "restart" ]; then
	kill "$(cat $pid)"
	rm -f "$pid"
	./manage_my_process &
	echo $! > "$pid"
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
